### ISSUE TITLE
Design for Import/Export APIs to replace storage plugins

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1585]
This issue has been raised by @martin-lysk. We agreed that importers/exporters is the right way to go but decided at the Berlin Offsite in Oct 23 to work around the issue as long as possible. First users are confused now why they storage plugins are limiting them.  

## Problem 

Inlang's set up to be "provide your storage plugin" leads to numerous issues: 

- inlang's features are limited by the provided storage plugin (a no-go)
- users don't understand why certain features work or don't work with a provide storage plugin (e.g. https://github.com/inlang/monorepo/issues/1577#issuecomment-1791655712)

## Proposal 

Storing messages should be controlled by the SDK to ensure that inlang is not limited by external plugins. 

- `loadMessages` should be succeeded by `importMessages`
- `saveMessages` should be succeeded by `exportMessages`
```
message-29sn82
-> json import: login.button
-> paraglide export: login_button
-> ios export: LOGIN_BUTTON
-> android export: login-button
```

**Pros**

- inlang is not limited by external plugins
- import/export APIs can expose what features they support
- multi-platform exports (export for iOS, Android, Paraglide) become possible
- users are communicated what is supported by a target platform and what not. 
- we can performance optimize the storage instead of naively calling `saveMessages()` and `loadMessages()`
- importer/exporter plugins could store additional data like message id `ieb3s` should be exported as `login-button`, or `ieb2s` exists in the namespace file `en/login.json`. requires https://github.com/inlang/monorepo/discussions/1418

**Cons**

- effort. 
- the introduction of https://github.com/inlang/monorepo/discussions/1418 should be completed with this change too. have a `project.inlang` folder to avoid massive scatter across a repo

## Requirements

- [ ] allow multiple importers and exporters to be used in a project (load and save messages only support one "storage" plugin at a time)
- [ ] must allow for "namespacing" logic see https://github.com/inlang/monorepo/issues/1577#issuecomment-1791655712. otherwise existing projects can't migrate to inlang 
- [ ] https://github.com/inlang/monorepo/issues/1769#issuecomment-1830270023
- [ ] when is export triggered? onSave [can be ignored for now]
- [ ] how to deal with creation/deletion

**Comment by samuelstroschein** [comment]
@martin-lysk this seems to be a great issue for you. after all, you raised this issue and now it is hurting our growth because users don't understand why feature limitations exist for different storage formats

**Comment by felixhaeberle** [comment]
As discussed in Berlin, this would be a API which finally solves limitations by external plugins and is therefore a good thing.

What (breaking) code change does this mean?

**Comment by martin-lysk** [comment]
I try to get the whole picture - collecting the inputs from the tickets referenced it seems like you have a concept on how this should be integrated already. Before I make a proposal that might not meet your thoughts - Shall we have a kickoff about that issue @samuelstroschein?

Open questions:

> Storing messages should be controlled by the SDK to ensure that inlang is not limited by external plugins.

- So inlang should come "with batteries included" and defines a default way to load messages and save messages? Shall plugins be able to override this behaviour at all?

> loadMessages should be succeeded by importMessages
> saveMessages should be succeeded by exportMessages

So instead of loading and saving messages (persistance) plugins would import / export messages from sources like  like sting.dict files or even api like poeditor/localize etc. The messages imported would than be managed by the inlang sdk and stored in the .inlang folder?

**Comment by samuelstroschein** [comment]
hey @martin-lysk 

- The "inlang directory" change should happen before this task https://github.com/inlang/monorepo/discussions/1418. 
- I have yet to write a proposal for the directory stuff. Planned to do that early next week. 
- The directory proposal will make changes to the message format really easy so we don't have to worry about one big json or not

When would you start with this/the to be proposed directory change so that I know when to write my proposal ?

**Comment by martin-lysk** [comment]
I guess the planned iterations in https://github.com/inlang/monorepo/issues/1459#issuecomment-1801904162 will keep me busy this week - I could have a look next week tuesday.

**Comment by samuelstroschein** [comment]
@martin-lysk okay i intend to publish more "inlang directory" proposal monday/tuesday which I would give you to implement. afterwards, the import/export stuff can be handled

**Comment by felixhaeberle** [comment]
@samuelstroschein @martin-lysk @janfjohannes What's the status here? Who is leading the importer/exporter & should be assigned?

**Comment by janfjohannes** [comment]
@felixhaeberle  see smuals comment: https://github.com/inlang/monorepo/issues/1585#issuecomment-1802405547

**Comment by samuelstroschein** [comment]
@felixhaeberle my directory implementaiton will come first. progress can be tracked in the https://github.com/inlang/monorepo/tree/1678-project-directory branch

**Comment by samuelstroschein** [comment]
@NiklasBuchfink i created https://github.com/inlang/monorepo/issues/1817. Let's keep this issue for importer/exporter only.

**Comment by martin-lysk** [comment]
@samuelstroschein whats your take on the scope here? shall we just add importers exporters to inlang sdk and keep the storage topic completely out of the scope of this issue? If so we would still need a plugin that provides load and save method right?
 
### Open questions:

What will become the execution points for importers / exporters - when shall we trigger an import or an export?

#### Only If storage is part of the ticket (if not we can answer those later):
  - should the change be backward compatible / should plugins loadMessage and saveMessages marked as deprecated as part of this 
  - since we plan to reimplement the save logic and it will most likely need a migration for existing projects i would iterate on the target persistance format first

### Thoughts on import/export triggers:

Compared to the current setup that only accepts one load and one save - importers and exporters will coexists. Projects may have an ios exporter **and** an android exporter **and** a json exporter all configured in one project. 
Compared to save and load, where save triggered on each change and load that is executed by the watcher and initially  exports/imports are usually triggered externally and not by events coming from the sdk:

### Use cases for Export Plugins
- triggers when configured within a ci pipeline as part of the cli
- a button within the editor to trigger an export
- a button in the editor that a allows a developert to download the localization files 
- ... any hooks in the sdk that an exporter should be triggered on?

### Use cases for Import Plugins
- a cli command that allows to import all keys from an existing set of messages - like ios/android/....
- an external webhook (like one from lokalise https://developers.lokalise.com/docs/webhook-events#projectkeymodified that updates the keys) intagration - this would most likely only be a trigger to an import
- an upload of an file like ios strings file within the editor 
- ... do you see any triggering of an import other than external ones?

**Comment by samuelstroschein** [comment]
@martin-lysk do you think a sync call where we draft spec in google docs is quicker than github back and forth? If so, let's schedule a call

**Comment by samuelstroschein** [comment]
Issue #1844 will be completed before this one.

**Comment by samuelstroschein** [comment]
## Proposal - introduction of aliases via amap

Introduce an alias map plugins can use to establish a relationship between message id and exported/imported key name. 

**Pros***

- plugins can make use import/export keys
- apps can display and edit "alias for i18next is login.button" because the plugin id is known  

**cons**

- ?

```diff
const message = {
  id: "human_airplane_globe", 
+  alias: {
+    plugin.inlang.i18next: "login.button",
+    plugin.inlang.xml: "login-button"
+  }
}
```
