### ISSUE TITLE
[bug] Support VS Code extension in Cloud IDE GitPod

### ISSUE THREAD

**Issue by mmailaender** [opral/monorepo#1637]
### Problem

We're using VSCode Cloud (GitPod) and the Inlang Vscode extension is not working
![image](https://github.com/inlang/monorepo/assets/87228994/7a101b90-1338-494c-a17d-a3f02e73ab6c)
![image](https://github.com/inlang/monorepo/assets/87228994/4598c51e-48f3-4228-a678-badf236b5863)

### Expected behavior

No error - Working extension

### Reproduction

@felixhaeberle  already reproduced it

### Other information

Environment: GitPod (Ubuntu LTS 22)
VSCode Cloud: 1.84.2

**Comment by felixhaeberle** [comment]
@mmailaender Thanks for the bug report. More context can be found here: https://discord.com/channels/897438559458430986/1173918606975840286/1173940400654917653

**Comment by felixhaeberle** [comment]
Further information: 

1. Fixing this bug requires building a vscode installable file from the provided link, because the GitPod currently does not have the inlang extension: https://github.com/inlang/monorepo/tree/main/inlang/source-code/ide-extension

2. Upload the vs code extension to GitPod and debug, why the inlang extension is not working.
This requires an inlang demo project with a `project.inlang.json`, which can be found here: 
https://github.com/inlang/monorepo/tree/main/inlang/source-code/paraglide/paraglide-js-adapter-sveltekit/example

Additional info: The problem is most likely that we use node fs in the vs code extension, what has to be replaced with `workspace.fs` because no node fs API is available in GitPod. The API can be found here: https://code.visualstudio.com/api/references/vscode-api#FileSystem

/bounty $20

**Comment by felixhaeberle** [comment]
The requirement for the bounty is an implementation of the code, a unit test of the fs functionality & a video that it's working in GitPod (cloud) & VS Code (locally) at the same time.

**Comment by felixhaeberle** [comment]
@ezhil56x You can attempt 👍

**Comment by felixhaeberle** [comment]
@ezhil56x Can you verify with a video that the behavior is working? Then the problem is probably rooted in some other circumstance. cc @mmailaender

**Comment by felixhaeberle** [comment]
@ezhil56x Any progress here? I would open this for other people also.

**Comment by ezhil56x** [comment]
> @ezhil56x Any progress here? I would open this for other people also.

I was not able to build the extension as vsix package. Can you guide me how to build vsix package so that I can import it is gitpod and test it. Requested help on discord ✨

**Comment by felixhaeberle** [comment]
[Here](https://github.com/inlang/monorepo/blob/main/CONTRIBUTING.md) are the conributing docs. The build can be executed with [this](https://github.com/inlang/monorepo/blob/2780a4957d389bcb697d5c2e6f80f756c85c346d/inlang/source-code/ide-extension/package.json#L68) command.

**Comment by jkcs** [comment]
@felixhaeberle If no one is doing it, you can assign it to me.

**Comment by jkcs** [comment]
> > @felixhaeberle If no one is doing it, you can assign it to me.
> 
> The internal team is working on migrating the node fs. So this will be in hold till then

Okay, may I know where you obtained this information from?

**Comment by ezhil56x** [comment]
> > > @felixhaeberle If no one is doing it, you can assign it to me.
> > 
> > The internal team is working on migrating the node fs. So this will be in hold till then
> 
> @ezhil56x Okay, may I know where you obtained this information from?

Discord channel

**Comment by felixhaeberle** [comment]
@ezhil56x @jkcs @mmailaender @alankritdabral 

this works now thanks to GitPod who upgraded their VSCode to v1.87.0 🥳

<img width="1279" alt="Bildschirmfoto 2024-03-12 um 18 00 10" src="https://github.com/opral/monorepo/assets/34959078/88c77add-aa26-44b1-b866-c8b66c914ac3">
