### ISSUE TITLE
Split languages on a per message basis

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#1817]
## Problem 

We bundle all languages of a message in "one message":

1. Does not align with user understanding of "one message related to one language"
2. Likely won't align with business needs where "messages" for different language tags are separate
3. Because of 1 and 2 we will likely build wrong abstractions that will be hard to change in the future. 
-- example 1 performance issues https://github.com/inlang/monorepo/issues/1585#issuecomment-1838083576 when editing "one message" that triggers all languages to re-render (might be mitigated in another way, but splitting per language should fix this issue)
-- example 2 hacky code that splits messages per language https://github.com/inlang/monorepo/blob/68412dd62af6e9363187d2ca09b5c03686f779db/inlang/source-code/plugins/i18next/src/plugin.ts#L273-L282

## Proposal

Split messages on a per-language basis to avoid user/dev confusion and avoid building the wrong abstractions. 

## Additional information 

One such solution could be the introduction of a "Message Bundle". See this loom https://www.loom.com/share/4ac1ad8060914ab689be7ac4ed755f95. 

```
.
└── Message Bundle (BLUE_HUMAN_ELEPHANT)
    ├── Message (DE)
    ├── Message (EN)
    │   ├── Variant [male,*]
    │   ├── Variant [female,*]
    │   └── Variant [*,*] 
    ├── Message (FR)
    └── ...
````

**Comment by felixhaeberle** [comment]
> Split messages on a per-language basis to avoid user/dev confusion

Imo, it doesn't matter which data structure is chosen here, at some point the chosen one (per-message, per-language) will fail based on the processing task.

> pricing models of paying "per message" are confusing

Maybe, but it should not influence our data structure at all. Pricing can be made however we like.

> leads to hacky code that splits messages per language

Exactly, annoying and leads to bugs.

---

You already mentioned it: we need, at best, message-message relations. This is also where "sdk persistency" could come into play.

**Comment by felixhaeberle** [comment]
@martin-lysk Is there an update on this?
cc @samuelstroschein

**Comment by samuelstroschein** [comment]
_Ergh. Thinking about this again... A message should likely be split by language tag. Thanks for the ping @felixhaeberle._

**Watch this loom https://www.loom.com/share/4ac1ad8060914ab689be7ac4ed755f95?sid=1f8e9b33-2315-46e1-944f-0462ed4ad7e3**

@jldec @martin-lysk we risk a (soonish) refactor of the data message structure or evaluate the introduction of a Message Bundle (or similar) now for message persistency v1? 

We will have to split messages by languages in the long run to align with user expectations and, more importantly, business needs. A message in one language might be completely unrelated to "the source message". The separation applies to various functionalities.

A good example are lint rules. It is obvious that lints rules should be adjustable both on a "per message (language)" level and "for all messages (in that bundle)".  

![CleanShot 2024-02-05 at 11 39 36@2x](https://github.com/opral/monorepo/assets/35429197/f4be51dc-600d-4d98-a73c-d8c54aa1e884)

**Comment by jldec** [comment]
just tuning into this discussion - feels like we need to separate the "user-level" (domain) model from both the internal cross-app sdk model, and separate that again from the persistence model.

#### user-level
- projects
- languages
- units of translation

#### sdk level
- project api
- language api
- message api

#### storage level
depends on the medium
- text files in git: one file per message, with all languages
- db: something more normalized

**Comment by martin-lysk** [comment]
I wouldn't hop into this deeper at the moment.

The current PR that aimed persistence was reduced to an id and a default aliase (and proper save/load) only.
The cool thing here: the id's are designed to not change when we persist them - and they are stable for a message name already. this allows us to address messages.

We can Adress messages and there variants by the id, followed by the locale and its matcher and this should be enough to deactivate lint rules on variant level already.

as response to the loom:

First, it doesn't align with user expectation.

From all exchanges and my own experience in teams i had so far I would state:
User expectation coming from the same origin as the - give that "thing" a name. Its one place in the UI that should express something the app/website/program is trying to give the user a textual input. Like "Login" - (The text should allow the user to understand: if i press here i get logged in). This input (from the program) tor the user can most likely be expressed in  other languages by a word or term that has a similar meaning. So you define one "login_button_label" (yes everybody hates the naming here) message and you ask translator to translate this message into another language - so you have it, THE MESSAGE, in multiple languages now.

This can become more tricky if its a informal text where gender and amount of some value plays role. But it's the same "party_invite_info_text" that has a variant "Lisa invited 5 people to HER party" or "Felix invited 3 people to his party" or "Martin hat noch niemanden zu seiner Party eingeladen". 

Second, it most likely will not align with business needs. 

It does - the cases where we cant address it with a variant in another language is an exception and will most likely end up in a new ui (because you cant express the same thing with a button or a label in the screen - you need mor) and therefore in a new message (that may only exist in the "problematic" language)!

And third, because, it doesn't align with user and business needs

not sure if i missed this in the loom

As a sidenode - all iteration trying to find a better term than message - will end up here again. Messages tab was called "Keys" in Parrot in Version 1 and nobody got it - I didn't had this issue with Messages so far.

**Comment by martin-lysk** [comment]
> Seems like we can achieve better querying by incrementally adding an ID to variants, or maybe do it now @martin-lysk ?
A variant can be addressed by its matcher - introducing an id on this level would need to be predictable based on - (the  matcher) to be able to merge / sync (compare to the human_id) and it wouldn't add any value by that. 

The good thing - I don't see any situation where the matcher is not enough - do you have an example that would be problematic?

**Comment by jldec** [comment]
> No replies needed below
👍

**Comment by samuelstroschein** [comment]
> @martin-lysk A variant can be addressed by its matcher 

This is not true. I created a follow-up issue #2186
