### ISSUE TITLE
fix badge constantly running out of memory

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2074]
## Problem 

The badge can oftentimes not be rendered because the server is constantly running out of memory.

![CleanShot 2024-01-22 at 11 11 03](https://github.com/opral/monorepo/assets/35429197/86c3e336-851a-4b34-9526-5bcf42f8b488)

## Proposal

Fix the badge. 

### Additional information

I suspect a memory leak because the cache is set to 250MB and the memory is 2GB, but the server is constantly crashing.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink assigning you because this is a growth opportunity for fink. you can ask jan for help if you need it

**Comment by janfjohannes** [comment]
finally solved.

- bug: svg renderer outdated and had more than 1gb base consuption and mem leark > update reduces to 300MB to 600 bse
- bug : caching had time conversion bug and only cached 1/1000 th day instead of one  day (ms instead of s)
- bug: did not cache errored repos which lead many repos with errors to DDOS badge server by retrying, implemented 2h error caching

you can clearly see the two bug fixes being deployed in first mem usage going flat to 900 mb and then dropping to 500.


![Screenshot 2024-01-24 at 20 41 53](https://github.com/opral/monorepo/assets/110794494/0c8d6cbd-6f22-48c7-aa5c-76a6474d799e)
