### ISSUE TITLE
[Nuxtjs] SDK Fails to load modules when using Nuxt

### ISSUE THREAD

**Issue by harrytran998** [opral/monorepo#2133]
## Problem 

When I tried to integrate the Paraglide with Nuxt 3, seem to paraglide was not detected in the locales. Hope you can double-check on this! Here is the message I received:

```bash
 WARN  No messages found - Skipping compilation into ./internationalization/paraglide                                                            
```

The `project.inlang` folder already setting the `pathPattern` is `"./internationalization/{languageTag}.json"`

```json
{
  "$schema": "https://inlang.com/schema/project-settings",
  "sourceLanguageTag": "en",
  "languageTags": ["en", "vi"],
  "modules": [
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-identical-pattern@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js"
  ],
  "plugin.inlang.messageFormat": {
    "pathPattern": "./internationalization/{languageTag}.json"
  },
  "messageLintRuleLevels": {
    "messageLintRule.inlang.missingTranslation": "error",
    "messageLintRule.inlang.validJsIdentifier": "error"
  }
}
```

Reproduction Repo: https://stackblitz.com/~/github.com/harrytran998/nuxt-paraglide

Hope the core team can help me with this problem. I will create a Nuxt Modules and example for Nuxt3 if this problem solved 😆

**Comment by NiklasBuchfink** [comment]
I have assigned @LorisSigrist as he is responsible for Paraglide JS :)

**Comment by harrytran998** [comment]
> I'm investigating. This seems like a bug in the vite-plugin / sdk at first glance.
> 
> Edit: The CLI still seems to work, so for the moment you can use
> 
> ```
> paraglide-js compile --project ./project.inlang --outdir internationalization/paraglide
> ```
> 
> in your `build` script.

Here is the output when I run your suggest command

```bash
ℹ [paraglide] Compiling inlang project at "./project.inlang".                                                                                   
file:///Users/project_folder/node_modules/@inlang/paraglide-js/dist/index.js:25260
    throw new Error(
          ^

Error: Cannot compile message with ID "apply.abroad".

The message is not a valid JavaScript variable name. Please choose a different ID.

To detect this issue during linting, use the valid-js-identifier lint rule: https://inlang.com/m/teldgniy/messageLintRule-inlang-validJsIdentifier
    at compileMessage (file:///Users/project_folder/node_modules/@inlang/paraglide-js/dist/index.js:25260:11)
    at file:///Users/project_folder/node_modules/@inlang/paraglide-js/dist/index.js:29207:18
    at Array.map (<anonymous>)
    at compile (file:///Users/project_folder/node_modules/@inlang/paraglide-js/dist/index.js:29206:42)
    at executeCompilation (file:///Users/project_folder/node_modules/@inlang/paraglide-js/dist/index.js:29550:18)
    at Command.<anonymous> (file:///Users/project_folder/node_modules/@inlang/paraglide-js/dist/index.js:29527:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.10.0
error: "paraglide-js" exited with code 1
```

The file in `src/compiler/compileMessage.ts`.

I log the the message form the message param in `compileMessage` function 

```
compileMessage  👻  message: {
  id: 'about',
  selectors: [],
  variants: [
    { languageTag: 'en', match: [], pattern: [Array] },
    { languageTag: 'vi', match: [], pattern: [Array] }
  ]
}
compileMessage  👻  message: {
  id: 'apply',
  selectors: [],
  variants: [ { languageTag: 'en', match: [], pattern: [Array] } ]
}
compileMessage  👻  message: {
  id: 'apply.abroad',
  selectors: [],
  variants: [ { languageTag: 'en', match: [], pattern: [Array] } ]
}
```

**Comment by harrytran998** [comment]
Oh, my bad - Thank you for your quick response! Hope you can solve this soon <3

**Comment by jldec** [comment]
@LorisSigrist I pushed a `nuxt-debug` branch to help debug this issue, but I'm stuck on getting the debugger past the vite-adapter / unplugin. https://github.com/opral/monorepo/tree/jldec/nuxt-debug. The branch includes a launch config which repro's the issue - maybe you can try it to see if you get further. 

My (very speculative, likely wrong) theory is the the vite plugin is not being loaded properly because of some ESM build incompatibilty. That theory is based on setting a breakpoint in the `loadProject()` call in `inlang/source-code/paraglide/paraglide-js-adapter-unplugin/dist/index.js` and observing a strange error message when that is hit in VS Code.

**Comment by LorisSigrist** [comment]
@jldec I found where the issue occurs. In the SDK in `resolveModules` the module resolution quietly fails & returns the stringified import error instead of the module code. Still figuring out why, but it's progress

**Comment by LorisSigrist** [comment]
@jldec I figured out where & why this error happens, but I have no idea how we can fix it, because it seems to be a nuxt issue.

The problem is that the async import in `sdk/src/moduleResolution/import.ts` is quietly failing to import the data-url encoded `inlang-message-format` module. This only happens in nuxt, because nuxt uses `unjs/jiti` for module-loading, which apparently fails when importing data-urls. I don't see how we can disable that. 

We could maybe side-step this issue if the SDK were to cache the modules locally & read them from disk. Is offline support on our roadmap? 

I'll switch the label to an SDK issue since this isn't caused by paraglide directly

**Comment by samuelstroschein** [comment]
> Is offline support on our roadmap?

https://github.com/opral/monorepo/discussions/1021

**Comment by matthiasbaldi** [comment]
I think the same issue happens with the vite integration when I try to use paraglide with solidJS.

**Comment by aguilera51284** [comment]
solid-start have the same error :)

**Comment by samuelstroschein** [comment]
@NiklasBuchfink this is likely the same problem you are facing. namely: dynamic import with JS data URIs failing.

@LorisSigrist did you identify the JS data URI dynamic import as root cause? If so, pushing offline caching of modules should probably be prioritized. Offinline caching = module is fetched, written to disk, and imported from disk (not via data URI)

**Comment by LorisSigrist** [comment]
Yes, the data URL dynamic imports are causing this. 
This happens because Nuxt overrides the `import` function with a non-standard one that breaks for data URLs when loading the configuration (they do this to allow importing TS files & transpile on the fly).

**Comment by LorisSigrist** [comment]
FIY We still plan to fix this, but the issue has been moved to Linear

**Comment by minht11** [comment]
Is there still a plan to fix it?
