### ISSUE TITLE
[bug] ide extension finds no messages – unify `normalPath` & `normalizePath`

### ISSUE THREAD

**Issue by samuelstroschein** [opral/monorepo#2184]
### Problem

<img width="335" alt="CleanShot 2024-02-06 at 12 24 51@2x" src="https://github.com/opral/monorepo/assets/35429197/b3fae0a7-b1d7-4a4d-8d02-d56a7f9c22ca">

### Expected behavior

Displays messages

### Reproduction

1. Clone https://github.com/opral/example
2. Open the project in the extension

### Other information

Fink can open the repo and project just fine https://fink.inlang.com/github.com/opral/example

**Comment by felixhaeberle** [comment]
@samuelstroschein There is no m or t syntax module defined.

**Comment by samuelstroschein** [comment]
@felixhaeberle so? messages in the project exist and should be shown. the bug report is not about inline annotations

**Comment by felixhaeberle** [comment]
Obviously the extension crashes somewhere because the customApi has to be set in the rendering of the messages view. 

Of course we could make it more modular here but in general please just setup the project correctly and then it works. The extension requirement until this date wasn't to work without a matcher (at all).

For this bug, I will investigate why messages do not load and load them. It's probably nice to split the functionality here if people miss the matcher.

**Comment by samuelstroschein** [comment]
> Of course we could make it more modular here but in general please just setup the project correctly and then it works. The extension requirement until this date wasn't to work without a matcher (at all).

The project is setup correctly? 

The custom API can be undefined ofc. Add an undefined check and you should be good to go.

**Comment by felixhaeberle** [comment]
Again, the project is not set up to work with the ide extension (yet) because it was no requirement to have the ide extension working without the matcher, so the logic wasn't encapsulated there. 

This will change with this issue so that the matcher can be undefined. The added features around the message tab allow this kind of loose matcher definition.

**Comment by felixhaeberle** [comment]
@jldec This is likely an SDK bug. I have successfully initialized the project but the `query.messages.getAll` query doesn't return messages.

<img width="766" alt="Bildschirmfoto 2024-02-15 um 11 07 59"
<img width="582" alt="Bildschirmfoto 2024-02-15 um 11 07 43" src="https://github.com/opral/monorepo/assets/34959078/a196ac25-3938-4381-bf77-8438a91869c2">
 src="https://github.com/opral/monorepo/assets/34959078/c5c6174f-0688-4ced-8cba-058f2e3f0034">
 
cc @samuelstroschein I don't know why Fink is working here, but for me the SDK doesn't return messages.
https://fink.inlang.com/github.com/opral/example

Is the above usage of the API correct?

**Comment by felixhaeberle** [comment]
found the reason for this. the `pathPattern` has to be a relative path of course.

current, not working pathPattern: `/resources/{languageTag}.json`
correct pathPattern: `**.**/resources/{languageTag}.json`

**Comment by janfjohannes** [comment]
will do

**Comment by felixhaeberle** [comment]
@janfjohannes any update to this?:)

**Comment by janfjohannes** [comment]
@felixhaeberle  i keep tickets up to date usually, no need to ping for updates unless something changes on your end eg. new info or reason something gets much higher prio etc.

**Comment by janfjohannes** [comment]
@felixhaeberle  assigning you back as i dont know what the other parts of this ticket are about, feel free to reach out if i can help with something else
