### ISSUE TITLE
add "use this action" on marketplace/readme of ninja github action

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#2317]
## Proposal

Give a native quick link to an action which users are familiar with in the github styling to have a very integrated feeling of the Ninja action from our marketplace into the GitHub Action marketplace. This button can be generated on this website https://buttons.github.io/ an could enhance the UX of the users who quickly want to get the action in their repository.

<img width="1166" alt="Bildschirmfoto 2024-02-29 um 16 17 18" src="https://github.com/opral/monorepo/assets/34959078/7f949df3-28fb-4184-aa20-f2aba94131c9">

*cc @NiklasBuchfink please create scope: inlang/ninja-action label*

**Comment by NiklasBuchfink** [comment]
@felixhaeberle Do you mean, you want this button instead of the `open` button on our normal website button? Similar to your "install it on vc code" button?

I think the need for the button is questionable as actions can be set up more easily by copying and pasting the example from the README.

Atm the README is the same on the website, the repo and the GitHub marketplace. This will change in the same way sherlock has two READMEs.

**Comment by felixhaeberle** [comment]
feel free to close then. reasonable answer 👍
