### ISSUE TITLE
[feature] warning for closing when unsynced data is present

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/monorepo#714]
**Problem**
Currently, when editing a translations in the editor, there is no warning or confirmation prompt if the user tries to leave the page with unpushed changes. This can lead to accidental loss of work or unsaved changes.

**Expected behavior**
The user should confirm a browser prompt before using:
1. leaves the page
2. closes the site

**Solutions** 
A warning when closing or leaving Fink with unpushed changes

**Comment by NiklasBuchfink** [comment]
No, not yet

**Comment by NiklasBuchfink** [comment]
@inlang/editor @samuelstroschein @felixhaeberle 

How should we continue with this? We thought saving the current "local changes" state inside the local storage would better fix the data loss issue.

**Benefits:**
- better UX (no alerts, no data loss, expected app behavior)
- display unpushed changes in `/editor` overview

**To keep in mind:**
When you return to a project that has received updates in the remote repository, the local changes must be applied properly.

**Comment by samuelstroschein** [comment]
@NiklasBuchfink I vote for implementing this issue as simple interim fix. 

implementing #1042 is high effort and will take long/is not a priority at the moment.

**Comment by jannesblobel** [comment]
This problem occurred because a user closed the website without pushing the translated messages, right?

Honestly, the easiest way, in my opinion, is to use an alert if the users try to leave the page. 

On an advanced level, you are right; we should save the changes locally. But as you mentioned, how do we deal with changes on the remote? And this option more complicated cases and potential bug possibilities. 


Proposal: 
If the Page detects unpushed changes, let's display this alert with messages like: 
"Houston, we have a problem; your changes are not saved. If you leave, your changes are lost." 
Space for creativity, but you get my point :) 
<img width="678" alt="CleanShot 2023-07-17 at 01 05 38@2x" src="https://github.com/inlang/inlang/assets/72493222/e5d250aa-320c-4557-bf0a-054f91e32ff6">

**Comment by NiklasBuchfink** [comment]
@jannesblobel I tried to implement this and it is not that easy because we have client-side navigation, a client-side app and a server-side website. It's not that easy to catch all cases of leaving the page. I also don't want to add editor-dependent code to the navigation and footer for each link to solve this.

**Easy:**
- reload/close the tab (beforeUnloadEvent)

**Complex:**
- browser navigation
- navigating away with vite-plugin ssr / links within the page

**Comment by NiklasBuchfink** [comment]
I hand this over to @inlang/lix

**Comment by samuelstroschein** [comment]
the issue title does not align with the proposal. the "real" proposal is here https://github.com/opral/monorepo/discussions/1042#discussion-5378830. 

update this issue description?

**Comment by janfjohannes** [comment]
@samuelstroschein  @NiklasBuchfink   i think it is still helpful to have logic in finks that warns users. this will also be useful when we have persistent in browser fs as it would be still helpful for users to know they will close a page without having pushed the changes , even if they will not lose them, just maybe forget they are in the local store.

suggestion: 

- make this ticket a fink ticket to just add the warning for closing when unsynced data is present
- convert the discussion into the lix feautre for persistent browser fs
